#cloud-config
packages:
  - python3
  - git
  - haproxy
runcmd:
  - echo "Task Initiated" > /tmp/init.log
  - cd /home/ec2-user
  - pwd >> /tmp/init.log
  - sudo yum update
  - sudo yum install -y gcc python3-devel
  - sudo pip3 install boto3 >> /tmp/init.log
  - git clone https://github.com/mitre/caldera.git --recursive --branch 4.1.0 >> /tmp/init.log
  - chmod 7777 caldera >> /tmp/init.log
  - cd caldera >> /tmp/init.log
  - pip3 install -r requirements.txt >> /tmp/init.log
  - pip3 install marshmallow-enum==1.5.1 >> /tmp/init.log
  - pip3 install ldap3==2.7 >> /tmp/init.log
  - pip3 install aioftp==0.21.4 >> /tmp/init.log
  - echo "Done" >> /tmp/init.log 
  - sudo sh -c 'python3 server.py & sleep 30; kill $!' &
  - sleep 30
  - sudo chmod 777 conf/local.yml
  - sudo sed -i '/^\s*red:\s/s/:.*/:\ LabPass1/' conf/local.yml
  - sudo sed -i '/^\s*blue:\s/s/:.*/:\ LabPass1/' conf/local.yml
  - sh -c 'python3 server.py & sleep 30; kill $!' &
  - sleep 30
  - echo "[Unit]" > /etc/systemd/system/caldera.service
  - echo "Description=Caldera C2 Service" >> /etc/systemd/system/caldera.service 
  - echo "" >> /etc/systemd/system/caldera.service 
  - echo "[Service]" >> /etc/systemd/system/caldera.service 
  - echo "User=ec2-user" >> /etc/systemd/system/caldera.service 
  - echo "WorkingDirectory=/home/ec2-user/caldera" >> /etc/systemd/system/caldera.service 
  - echo "ExecStart=/usr/bin/python3 /home/ec2-user/caldera/server.py" >> /etc/systemd/system/caldera.service 
  - echo "" >> /etc/systemd/system/caldera.service 
  - echo "[Install]" >> /etc/systemd/system/caldera.service 
  - echo "WantedBy=multi-user.target" >> /etc/systemd/system/caldera.service 
  - systemctl daemon-reload
  - systemctl start caldera
  - systemctl enable caldera
  - cat conf/local.yml | grep  -oP '^\s+red:\s(?<Password>[\w\d_\-]+)' > /tmp/password